import type { NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import React, { useCallback } from "react";
import { NoteContainer } from "~/components/NoteContainer";

const Home: NextPage = () => {
  const session = useSession();
  const user = session?.data?.user;

  const toggleSession = useCallback(() => {
    if (user == null) {
      signIn("github");
    } else {
      signOut();
    }
  }, [user]);

  if (session.status === "loading") return null;

  return (
    <>
      <button
        onClick={toggleSession}
        className="bg-indigo-500 py-2 px-4 border border-transparent rounded-md text-base font-medium text-white fixed top-4 right-4 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
        style={{
          zIndex: Number.MAX_SAFE_INTEGER,
        }}
      >
        {user == null ? "Sign In" : "Sign Out"}
      </button>

      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {session.status === "unauthenticated" ? (
        <h1 className="m-auto text-xl">Sign in to get started!</h1>
      ) : (
        <NoteContainer />
      )}
    </>
  );
};

export default Home;
